### ISSUE TITLE
Package version in kaliningraph.json no longer exists

### ISSUE THREAD

**Issue by sgilson** [breandan/kaliningraph#2]
I'm trying to import the lib into a jupyter notebook through %use, however, version 0.1.1 does not appear to be available on jitpack.io. Jupyter(v4.4.0) and the jupyter-kotlin-kernel (v 0.8.3.1) are both freshly installed.

<img width="697" alt="Screen Shot 2020-12-09 at 12 16 19 AM" src="https://user-images.githubusercontent.com/26096478/101603003-c4494f00-39b3-11eb-91ed-00a8386ba206.png">

I manually navigated to 0.1.4 in the browser as a sanity check and that works just fine.

I'll just explicitly import 0.1.4 for now, but I'm looking forward to having the renderers available :)

**Comment by breandan** [comment]
Hi @sgilson, thanks for checking out the project and reporting this issue! I have updated the [library descriptor](https://github.com/breandan/kaliningraph/blob/master/kaliningraph.json) to use the most recent version and simplified the notebook [installation instructions](https://github.com/breandan/kaliningraph#jupyter-notebook) in the readme. I will try to keep the [official library descriptor](https://github.com/Kotlin/kotlin-jupyter/blob/master/libraries/kaliningraph.json) up to date, but since the Jupyter kernel now supports using library descriptors from arbitrary URLs, you may also use the following line magic:

`%use @https://raw.githubusercontent.com/breandan/kaliningraph/master/kaliningraph.json`

as described in the [kotlin-jupyter readme](https://github.com/Kotlin/kotlin-jupyter#supported-libraries) to fetch the most recent version. This should allow you to use the custom notebook renders as described. Please do not hesitate to reach out if you encounter any further issues.
